[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py seed_consoles && gunicorn retrostore.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
DEBUG = "False"
ALLOWED_HOSTS = "web-production-c47e.up.railway.app,localhost,127.0.0.1,healthcheck.railway.app,*.railway.app" 